---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    replicas: 1
    hostNetwork: true
  services:
    cassandras:
    - metadata:
        name: cassandra1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""   
        serviceConfiguration:
          images:
            cassandra: cassandra:3.11.4
            init: python:alpine
            maxHeapSize: 1024M
            minHeapSize: 100M
    zookeepers:
    - metadata:
        name: zookeeper1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""   
        serviceConfiguration:
          images:
            zookeeper: docker.io/zookeeper:3.5.5
            init: python:alpine
    rabbitmq:
      metadata:
        name: rabbitmq1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""   
        serviceConfiguration:
          images:
            rabbitmq: rabbitmq:3.7
            init: python:alpine
    config:
      metadata:
        name: config1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""   
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          images:
            api: opencontrailnightly/contrail-controller-config-api:1910-latest
            devicemanager: opencontrailnightly/contrail-controller-config-devicemgr:1910-latest
            schematransformer: opencontrailnightly/contrail-controller-config-schema:1910-latest
            servicemonitor: opencontrailnightly/contrail-controller-config-svcmonitor:1910-latest
            analyticsapi: opencontrailnightly/contrail-analytics-api:1910-latest
            collector: opencontrailnightly/contrail-analytics-collector:1910-latest
            redis: redis:4.0.2
            nodemanagerconfig: opencontrailnightly/contrail-nodemgr:1910-latest
            nodemanageranalytics: opencontrailnightly/contrail-nodemgr:1910-latest
            nodeinit: opencontrailnightly/contrail-node-init:1910-latest
            init: python:alpine
    kubemanagers:
    - metadata:
        name: kubemanager1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""   
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          images:
            kubemanager: opencontrailnightly/contrail-kubernetes-kube-manager:1910-latest
            nodeinit: opencontrailnightly/contrail-node-init:1910-latest
            init: python:alpine
          useKubeadmConfig: true
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    controls:
    - metadata:
        name: control1
        labels:
          contrail_cluster: cluster1
          control_role: master
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""   
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          images:
            control: opencontrailnightly/contrail-controller-control-control:1910-latest
            dns: opencontrailnightly/contrail-controller-control-dns:1910-latest
            named: opencontrailnightly/contrail-controller-control-named:1910-latest
            nodemanager: opencontrailnightly/contrail-nodemgr:1910-latest
            nodeinit: opencontrailnightly/contrail-node-init:1910-latest
            init: python:alpine
    webui:
      metadata:
        name: webui1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""   
        serviceConfiguration:
          cassandraInstance: cassandra1
          images:
            webuiweb: opencontrailnightly/contrail-controller-webui-web:1910-latest
            webuijob: opencontrailnightly/contrail-controller-webui-job:1910-latest
            redis: redis:4.0.2
            nodeinit: opencontrailnightly/contrail-node-init:1910-latest
    vrouters:
    - metadata:
        name: vroutermaster
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""    
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          images:
            vrouteragent: opencontrailnightly/contrail-vrouter-agent:1910-latest
            vrouterkernelinit: opencontrailnightly/contrail-vrouter-kernel-init:1910-latest
            vrouterkernelbuildinit: opencontrailnightly/contrail-vrouter-kernel-build-init:1910-latest
            vroutercni: michaelhenkel/contrailcni:v0.0.1
            nodemanager: opencontrailnightly/contrail-nodemgr:1910-latest
            nodeinit: opencontrailnightly/contrail-node-init:1910-latest
            init: python:alpine
    - metadata:
        name: vrouternodes
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.opencontrail.org: "vrouter"  
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          images:
            vrouteragent: opencontrailnightly/contrail-vrouter-agent:1910-latest
            vrouterkernelinit: opencontrailnightly/contrail-vrouter-kernel-init:1910-latest
            vrouterkernelbuildinit: opencontrailnightly/contrail-vrouter-kernel-build-init:1910-latest
            vroutercni: michaelhenkel/contrailcni:v0.0.1
            nodemanager: opencontrailnightly/contrail-nodemgr:1910-latest
            nodeinit: opencontrailnightly/contrail-node-init:1910-latest
            init: python:alpine          
    contrailCommand:
      metadata:
        name: command
      spec:
        commonConfiguration:
          activate: true
          create: true
          hostNetwork: true
          tolerations:
            - effect: NoSchedule
              operator: Exists
            - effect: NoExecute
              operator: Exists
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          adminUsername: "admin"
          adminPassword: "contrail123"
