apiVersion: v1
kind: PersistentVolume
metadata:
  name: command-db-pv
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/volumes/psql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
  persistentVolumeReclaimPolicy: Retain
