apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 01-master-modules
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      directories:
        - path: "/opt/modules"
          mode: 0755
        - path: "/opt/modules.wd"
          mode: 0755
      files:
      - path: /etc/contrail/modules_overlay.sh
        mode: 0755
        user:
          name: root
        contents:
          # 'data:,' and URL encoded openshift-install/sources/nm_stop.sh
          source: data:,%23%21%2Fbin%2Fbash%0A%0Amount%20-o%20%22lowerdir%3D%2Flib%2Fmodules%2Cupperdir%3D%2Fopt%2Fmodules%2Cworkdir%3D%2Fopt%2Fmodules.wd%22%20-t%20overlay%20overlay%20%2Flib%2Fmodules
    systemd:
      units:
      - name: lib-modules-mount.service
        enabled: true
        contents: |
          [Unit]
          Description=Mount overlay for /lib/modules
          After=usr-lib-modules.mount
          AssertPathExists=/etc/contrail/modules_overlay.sh

          [Service]
          Type=simple
          ExecStart=/etc/contrail/modules_overlay.sh
          StandardOutput=syslog
          StandardError=syslog

          [Install]
          WantedBy=multi-user.target