---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 1
    nodeSelector:
      node-role.kubernetes.io/master: ""
    keystoneSecretInstance : cluster1-admin-password
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          containers:
            cassandra:
              image: cassandra:3.11.4
            init:
              image: python:alpine
            init2:
              image: cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            analyticsapi:
              image: opencontrailnightly/contrail-analytics-api:master.1175
            api:
              image: opencontrailnightly/contrail-controller-config-api:master.1175
            collector:
              image: opencontrailnightly/contrail-analytics-collector:master.1175
            devicemanager:
              image: opencontrailnightly/contrail-controller-config-devicemgr:master.1175
            dnsmasq:
              image: kaweue/contrail-controller-config-dnsmasq:dev
            init:
              image: python:alpine
            init2:
              image: busybox
            nodeinit:
              image: opencontrailnightly/contrail-node-init:master.1175
            redis:
              image: redis:4.0.2
            schematransformer:
              image: opencontrailnightly/contrail-controller-config-schema:master.1175
            servicemonitor:
              image: opencontrailnightly/contrail-controller-config-svcmonitor:master.1175
            queryengine:
              image: opencontrailnightly/contrail-analytics-query-engine:master.1175
            statusmonitor:
              image: apasyniuk/contrail-statusmonitor
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            control:
              image: opencontrailnightly/contrail-controller-control-control:master.1175
            dns:
              image: opencontrailnightly/contrail-controller-control-dns:master.1175
            init:
              image: python:alpine
            named:
              image: opencontrailnightly/contrail-controller-control-named:master.1175
            nodeinit:
              image: opencontrailnightly/contrail-node-init:master.1175
            statusmonitor:
              image: kaweue/contrail-statusmonitor:master-180ab9
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          create: true
          replicas: 1
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            provisioner:
              image: kaweue/contrail-provisioner:master.1175
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            rabbitmq:
              image: rabbitmq:3.7
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:alpine
            nodeinit:
              image: opencontrailnightly/contrail-node-init:master.1175
            redis:
              image: redis:4.0.2
            webuijob:
              image: opencontrailnightly/contrail-controller-webui-job:master.1175
            webuiweb:
              image: opencontrailnightly/contrail-controller-webui-web:master.1175
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          create: true
        serviceConfiguration:
          containers:
            init:
              image: python:alpine
            zookeeper:
              image: docker.io/zookeeper:3.5.5
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:alpine
            kubemanager:
              image: opencontrailnightly/contrail-kubernetes-kube-manager:master.1175
            nodeinit:
              image: opencontrailnightly/contrail-node-init:master.1175
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          useKubeadmConfig: true
          zookeeperInstance: zookeeper1
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermaster
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:alpine
            nodeinit:
              image: opencontrailnightly/contrail-node-init:master.1175
            vrouteragent:
              image: opencontrailnightly/contrail-vrouter-agent:master.1175
            vroutercni:
              image: apasyniuk/contrailcni
            vrouterkernelbuildinit:
              image: opencontrailnightly/contrail-vrouter-kernel-build-init:master.1175
            vrouterkernelinit:
              image: apasyniuk/vrouter-kernel-init
          controlInstance: control1
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouternodes
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.opencontrail.org: vrouter
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:alpine
            nodeinit:
              image: opencontrailnightly/contrail-node-init:master.1175
            vrouteragent:
              image: opencontrailnightly/contrail-vrouter-agent:master.1175
            vroutercni:
              image: apasyniuk/contrailcni
            vrouterkernelbuildinit:
              image: opencontrailnightly/contrail-vrouter-kernel-build-init:master.1175
            vrouterkernelinit:
              image: apasyniuk/vrouter-kernel-init
          controlInstance: control1
